on:
  push:
    branches:
      - main
      - dev # V3 deployment; remove this when V3 is stable
    paths:
      - "docs/**"
      - "packages/css/**"
      - "packages/react/**"
      - "packages/stackflow/**"
      - ".github/workflows/deploy-grape_design_react-storybook-prod-pages.yml"
      - ".github/actions/setup/action.yml"
  workflow_dispatch:

permissions:
  contents: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: deploy-grape_design_react-storybook-prod-pages

jobs:
  deploy:
    name: deploy-grape_design_react-storybook-prod-pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup
        with:
          build-packages: true

      - name: Build Storybook
        working-directory: ./docs
        run: bun build-storybook

      - name: Deploy docs at Cloudflare Pages in `grape_design_react-storybook` project (Production)
        run: |
          CLOUDFLARE_ACCOUNT_ID=${{ secrets.CF_ACCOUNT_ID }} \
          CLOUDFLARE_API_TOKEN=${{ secrets.CF_API_TOKEN }} \
          bun wrangler pages deploy ./docs/storybook-static --project-name=grape_design_react-storybook --branch=${{ github.ref_name }}

          