on:
  push:
    branches:
      - main
      - dev # V3 deployment; remove this when V3 is stable
    paths:
      - "docs/**"
      - "examples/stackflow-spa/**"
      - "packages/css/**"
      - "packages/react/**"
      - "packages/stackflow/**"
      - ".github/workflows/deploy-grape_design_react-stackflow-spa-prod-pages.yml"
      - ".github/actions/setup/action.yml"
  workflow_dispatch:

permissions:
  contents: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: deploy-grape_design_react-stackflow-spa-prod-pages

jobs:
  deploy:
    name: deploy-grape_design_react-stackflow-spa-prod-pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup
        with:
          build-packages: true

      - name: Build Stackflow SPA
        working-directory: ./examples/stackflow-spa
        run: |
          bun run build

      - name: Deploy stackflow-spa at Cloudflare Pages in `grape_design_react-stackflow-spa` project (Production)
        run: |
          CLOUDFLARE_ACCOUNT_ID=${{ secrets.CF_ACCOUNT_ID }} \
          CLOUDFLARE_API_TOKEN=${{ secrets.CF_API_TOKEN }} \
          bun wrangler pages deploy ./examples/stackflow-spa/dist --project-name=grape_design_react-stackflow-spa --branch=${{ github.ref_name }}

          