name: Test React

on:
  push:
    paths:
      - "packages/react/**/*"
      - ".github/workflows/react-test.yml"
      - ".github/actions/setup/action.yml"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup

      - name: Build common dependencies
        run: bun --filter @grape_design_react/dom-utils build && bun headless:build && bun --filter @grape_design_react/react build

      - name: Run tests
        run: bun react:test
